Change announcement api
pharo-spec/Spec pull request #1374
Opened 2023-04-04 14:26 UTC by PalumboN

We changed the Announcement API

```
when: event do: action
```
by
```
when: event do: action for: subscriber
```

See https://github.com/pharo-project/pharo/pull/13270 for more details

2023-05-03 22:36 UTC, jecisc requested changes

2023-05-03 22:36 UTC, jecisc commented on src/Spec2-Adapters-Morphic/SpAbstractMorphicAdapter.class.st
> -SpAbstractMorphicAdapter >> when: anAnnouncement do: aBlock [
Maybe we should do as in the PR of Pharo and keep the old version deprecated

2023-10-17 11:58 UTC, jordanmontt commented
The code seems ok :) there are just some comments to be fixed

2023-10-19 01:27 UTC, PalumboN commented
I close this PR because:
- [The change](https://github.com/pharo-project/pharo/pull/13590) in the Pharo repo was merged to pharo-12
- I wrote a deprecation rule for that, so the code should be already changed in pharo-12 branch (in this repo)
- Probably some improvements could be made on this side too, but I prefer to do it in another PR :)

2023-10-19 01:27 UTC, closed without merging